# Generated by Django 3.1 on 2020-10-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_statistics', '0002_auto_20201007_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststatistics',
            options={},
        ),
    ]
